name: phy
dependencies:
  - python=3.6
  - pip
  - pywin32
  - numpy
  - matplotlib
  - scipy
  - cython
  - six
  - colorcet
  - pandas
  - seaborn
  - ruamel_yaml
  - pytest
  - nose
  - jupyter
  - astropy
  - ipython
  - paramiko
  - click
  - h5py
  - tqdm
  - packaging
  - openpyxl
  - vispy
  - traitlets
  - joblib
  - requests
  - pyqt=5.9
  - git
  - pyopengl
  - scikit-learn
  - sip
  - xmltodict
  - pycodestyle
  - pip:
    - gitpython
    - pycircstat
    - quantities
    - pyrebase
    - tkfilebrowser
    - xmljson
    - scp
    - send2trash
    - pyintan
    - kbucket
    - mountainlab_pytools
    - klusta
    - klustakwik2
    - pycwt
    - elephant
    - -e git+https://github.com/CINPLA/python-neo.git@expipe#egg=python-neo
    - -e git+https://github.com/CINPLA/pyopenephys.git@master#egg=pyopenephys
    - -e git+https://github.com/CINPLA/expipe.git@dev#egg=expipe
    - -e git+https://github.com/CINPLA/pyxona.git@dev#egg=pyxona
    - -e git+https://github.com/CINPLA/expipe-cli.git@dev#egg=expipe-cli
    - -e git+https://github.com/CINPLA/exdir.git@dev#egg=exdir
    - -e git+https://github.com/CINPLA/exdir-cli.git@dev#egg=exdir-cli
    - -e git+https://github.com/CINPLA/expipe-plugin-cinpla.git@dev#egg=expipe-plugin-cinpla
    - -e git+https://github.com/CINPLA/expipe-io-neuro.git@dev#egg=expipe-io-neuro
    - -e git+https://github.com/CINPLA/expipe-templates-cinpla.git@master#egg=expipe-templates-cinpla
    - -e git+https://github.com/SpikeInterface/spikeextractors.git@master#egg=spikeextractors
    - -e git+https://github.com/SpikeInterface/spikesorters.git@master#egg=spikesorters
    - -e git+https://github.com/SpikeInterface/spiketoolkit.git@master#egg=spiketoolkit
    - -e git+https://github.com/cortex-lab/phy.git@dev#egg=phy
    - -e git+https://github.com/cortex-lab/phylib
